### ISSUE TITLE
Using responsive props weird behavior when using it as ui library

### ISSUE THREAD

**Issue by flozero** [nextui-org/tailwind-variants#198]
**Describe the bug**
If we introduce tailwind responsive props. If we want to make sure they are available outside of the project we need to import the css file of the ouput inside the main ts file inside the sandbox. And also add the js output inside the tailwind content inside the sandbox. Problem with that is that it creates duplicates and it seems random and inconsistent.

**To Reproduce**

Repo to work on with basic setup on how do we work
https://github.com/flozero/tailwind-variant-responsive

- `nvm use` root folder
- pnpm install at the root
- pnpm build inside `packages/ui`
- pnpm dev inside `packages/sandbox`

If you want to reproduce the bug:
- comment inside sandbox the safeList addition line 11 inside tailwind config
- run `pnpm build:withcss` instead of just build inside ui folder
- uncomment line 5 of `src/main.tsx` inside sandbox
- comment safelist inside ui tailwind config also

**Expected behavior**

when you use a library with tailwind we would expect to use the library this way:
- in the other project use the js output path of the lib inside the tailwind content config of sandbox
- use the component themselves
- thats it basically.

I am using the latest tailwind variant 2.1

**workaround we have worked on**
We decided to use tailwind safeList to enforce tailwind to add the css for responsive variants. With small works we can also exclude some responsive variant we dont want.

I know "responsive variants" is something really not common in tailwind community when they are used inside the library. I am open to any suggestions. But if you look at library like daisy ui and other the only thing they do is having a plugin.

I also do not use the withTV on the tailwind config as it looks like it brings other issues. I need to looks at what this code is doing. 

I kind of see you were reading files and extract things from it. Could you list me what this is doing maybe I could be better at fixing my issue of improve some stuff here.

Don't hesitate to ask clarification if its not clear enough. I will try my best

edit: I was looking at next ui but the project is using a old version of tailwind variant and do not use responsive variant.

Would be good to have so example project for it.

**Comment by flozero** [comment]
Hey @Kinbaum  we have created a package in my company that achive this really good If you want to have look

https://github.com/busbud/tailwind-buddy

**Comment by Kinbaum** [comment]
Thanks, I'll take a look at it. Though with respect to this library, I don't think this issue should be closed. The responsive variants is what really separates this library from `cva` and this issue is significant.

**Comment by Kinbaum** [comment]
I managed to set up everything for my specific case. To start, I used `tsup` to build my library and added a comment at the end of each JavaScript file with the name of my package `// @my-lib/ui`.

The reason behind this approach is that the transformer only looks at the content and checks if the `tailwind-variants` package is there. But since I'm working with a component library, all I had to work with were some compiled relative paths - nothing to indicate that this code belonged to my library. So, adding the comment provided a clear marker for targeting.

Next, I included a `transformerConfig` as the second argument to the `withTV` method. It's worth noting that TypeScript will throw an error due to incorrect function types, which I discovered while digging into the source code.

In the transformer config, I specified an `aliases` array that merges with the default `tailwind-variants` path lookup. Finally, I added my library's name as an alias, allowing the proper transformation of my responsive variants.
