### ISSUE TITLE
We have decided to offer an alternative project from this project

### ISSUE THREAD

**Issue by flozero** [nextui-org/tailwind-variants#203]
You have done a great job on this project and it was definitely working great at the time it was maintain. But we do need a bit more responsiveness on this as its core to one of our major product. 

We understand that its open source but as its under nextui we would have expect active maintainers and also that your main project would have use the latest version not a really old one.

We have created in my company a similar project with a different approach for it for people who would be interest in this. We will maintain it as its part of our design system.

https://github.com/busbud/tailwind-buddy

There is still work to do in the documentation that I will work on this week.

**Comment by mskelton** [comment]
There is a lot that goes into developing a library like this one, and maintainers can frequently have difficulty in keeping up based on other commitments in work/life. Rather than creating a separate project altogether, I'd recommend helping contribute to existing projects to growth the contributor community.

Maintaining open-source software is the job of the **community**, not just the "designated maintainers".

**Comment by flozero** [comment]
I understand your point. And totally fair as I am also maintaining other libraries

Unfortunately having a good communication about this would have been fair and honest to the community also and ask for maintainers. 

To be able to iterate fast and we do see some fundamental practices totally different. We will continue in our path. 

I hope you will be able to continue maintaining the library. wish you all the best
