### ISSUE TITLE
Leading classes not added to output

### ISSUE THREAD

**Issue by neefrehman** [nextui-org/tailwind-variants#47]
**Describe the bug**
I'm currently evaluating `tv` for a project, and have been doing some testing by refactoring an existing typography component. I've noticed that some classes (in this case, `leading-x` ones) aren't being added.

**To Reproduce**
[Here is a codesandbox](https://codesandbox.io/s/confident-http-rvdg8c?file=/src/index.tsx) with a minimal repro, showing that the leading classes are not added by `tv`, but are added by `cva`

**Expected behavior**
All classes listed in the variant's config are added to the output.

**Screenshots**

**Desktop (please complete the following information):**

- OS: MacOS
- Browser: Chrome, Safari
- Version: 0.1.5

**Comment by sillyleo** [comment]
Same here. It took me 6 hours+ to figure out what I was doing wrong... turns out it's not me.

**Comment by tianenpang** [comment]
Hi @neefrehman @sillyleo, thanks for the feedback.

This is caused by the default merging rules of `tailwind-merge` and we are using `tailwind-merge` to resolve class name conflicts. 

To resolve this issue, you could simply place `leading-` after `text-`, or refer to the [docs](https://www.tailwind-variants.org/docs/api-reference#config-optional) for customizing merge rules.

**Comment by neefrehman** [comment]
Thanks @tianenpang! I hadn't clocked the tailwind-merge section in the documentation. Happy to close this issue based on your comments.
