### ISSUE TITLE
Slot level variant overrides

### ISSUE THREAD

**Issue by mskelton** [nextui-org/tailwind-variants#48]
We are using react-aria-components in our component library and one thing we find that tailwind-variants doesn't support very well is the ability to override variants at the slot level.  For example, with react-aria-components, some variables used for variants are passed to the class name prop like shown below.

```tsx
const tooltipStyles = tv({ ... })
const styles = tooltipStyles()

<BaseTooltip className={({ placement }) => styles.base({ placement })}>
  <OverlayArrow className={({ placement }) => styles.arrow({ placement })}>
    <svg />
  </OverlayArrow>
  
  {content}
</BaseTooltip>
```

While this is more of a niche use case, and defining the variants at the top level is definitely the more likely case, having the ability to at least override variants at the slot level to support this use case would be nice.

Thoughts?

**Comment by jrgarciadev** [comment]
Hey @mskelton you can pass custom classes to the returned slots as follows:

```jsx
const tooltipStyles = tv({ ... })
const styles = tooltipStyles()

<BaseTooltip className={({ placement }) => styles.base({ class: placement })}>
  <OverlayArrow className={({ placement }) => styles.arrow({ class: placement })}>
    <svg />
  </OverlayArrow>
  
  {content}
</BaseTooltip>

```

You can use either `class` or `className`, here's how we used it in NextUI 

https://github.com/nextui-org/nextui/blob/feat/v2/packages/components/progress/src/use-progress.ts#L131

**Comment by schardev** [comment]
@jrgarciadev It'd be really great to have this feature implemented in TWV since it opens up a granular level of conditional styling for slots. Sure we can override it by using `className` (and it might have worked for @mskelton's use case) but what I think @mskelton meant by slot level overriding was something like this:


So suppose we have two buttons with a slot that changes styling based on an `active` prop, but we don't wanna have it on the base styles since both button relies on different state variables. Instead of overriding via `className` on each button, something like this would be great:

```jsx
const pageStyles = tv({
  slots: {
    button: "bg-white",
  },
  variants: {
    active: {
      true: {
        button: "text-green-500",
      },
      false: {
        button: "text-red-500",
      },
    },
  },
});

const Page = () => {
  const [someState, setSomeState] = useState(true);
  const [someOtherState, setSomeOtherState] = useState(false);
  const { button } = pageStyles();

  return (
    <>
      {/* instead of overriding className */}
      <button className={button({className: someState === true ? "text-green-500" : "text-red-500"})}>Hello World!</button>
      <button className={button({className: someOtherState === true ? "text-green-500" : "text-red-500"})}>Hello World!</button>
      {/* we should be able to do it like this */}
      <button className={button({active: someState === true})}>Hello World!</button>
      <button className={button({active: someOtherState === true})}>Hello World!</button>
    </>
  )
}
```

Let me know if there's a better way to do it :)
